const BUILT_IN = [
  {word:'because',sentence:'I wore my coat because it was cold.',pattern:'because'},
  {word:'beautiful',sentence:'The peacock has beautiful feathers.',pattern:'-ful ending'},
  {word:'different',sentence:'The two shells look different.',pattern:'double consonants'},
  {word:'important',sentence:'It is important to listen carefully.',pattern:'-ant ending'},
  {word:'thought',sentence:'I thought about the answer.',pattern:'-ough sound'},
  {word:'enough',sentence:'There is enough cake for everyone.',pattern:'-ough sound'},
  {word:'favourite',sentence:'Blue is my favourite colour.',pattern:'our spelling'},
  {word:'remember',sentence:'Remember to bring your reading book.',pattern:'prefix re-'},
  {word:'straight',sentence:'Draw a straight line with your ruler.',pattern:'-aigh sound'},
  {word:'surprise',sentence:'The party was a lovely surprise.',pattern:'-prise ending'}
];
const WORD_BANK = `accident actual address answer appear arrive believe bicycle breath breathe build busy business calendar caught centre century certain circle complete consider continue decide describe disappear early earth eight eighth exercise experience experiment extreme famous February forward fruit grammar group guard guide heard heart height history imagine increase interest island knowledge learn length library material medicine mention minute natural naughty notice occasion occasionally often opposite ordinary particular peculiar perhaps popular position possess possession possible potatoes pressure probably promise purpose quarter question recent regular reign sentence separate special strange strength suppose therefore though although through various weight woman women`.toLowerCase().split(' ');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let state={queue:[],index:0,records:{},coins:0,xp:0,boss:[],bossIndex:0,bossCorrect:0,locked:false};
const saved=JSON.parse(localStorage.getItem('spellQuest')||'{}');
$('#coinCount').textContent=saved.totalCoins||0; $('#starCount').textContent=saved.totalStars||0;
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id+'Screen').classList.add('active');scrollTo(0,0);if(id==='parent')renderParent()}
$$('[data-nav]').forEach(b=>b.onclick=()=>show(b.dataset.nav));
function currentWeek(){return Math.max(1,Math.min(10,Number(saved.activeWeek)||1))}
function planWords(week=currentWeek()){return ((saved.weeklyPlan||{})[week]||[]).filter(Boolean)}
function getWords(){const c=planWords();return (c.length>=5?c.map(word=>({word,sentence:`Can you spell the word ${word}?`,pattern:guessPattern(word)})):BUILT_IN).slice(0,15)}
function guessPattern(w){if(/ough/.test(w))return '-ough sound';if(/tion/.test(w))return '-tion ending';if(/ful$/.test(w))return '-ful ending';if(/ly$/.test(w))return '-ly ending';if(/([a-z])\1/.test(w))return 'double consonants';return 'whole word'}
function start(){const words=getWords(),stamp=Number(saved.weekStamp)||1;saved.wordHistory=saved.wordHistory||{};words.slice(0,10).forEach(x=>saved.wordHistory[x.word]=stamp);localStorage.setItem('spellQuest',JSON.stringify(saved));state={queue:words.slice(0,10).map((data,i)=>({data,mode:i%3,repeat:false})),index:0,records:{},coins:0,xp:0,boss:[],bossIndex:0,bossCorrect:0,locked:false};words.slice(0,10).forEach(x=>state.records[x.word]={attempts:0,firstCorrect:null,correct:false});show('game');renderQuestion()}
$('#startBtn').onclick=start;$('#playAgain').onclick=start;$('#exitBtn').onclick=()=>show('home');
function speak(word,sentence=''){if(!('speechSynthesis'in window)){setFeedback('Your browser cannot speak, but you can still play.',false);return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(sentence?`${word}. ${sentence}`:word);u.lang='en-GB';u.rate=.78;speechSynthesis.speak(u)}
function current(){return state.queue[state.index]}
function renderQuestion(){state.locked=false;const q=current();if(!q){startBoss();return}const {word,sentence}=q.data;$('#roundLabel').textContent=`Quest ${Math.min(state.index+1,10)} of 10`;$('#xpLabel').textContent=`${state.xp} XP`;$('#progressBar').style.width=`${Math.min(100,(state.index/state.queue.length)*100)}%`;$('#feedback').textContent='';$('#feedback').className='feedback';$('#owlText').textContent=q.repeat?'This one is back for another try — you’ve got this!':'I’m with you! Have a go.';
  if(q.mode===0){$('#modeBadge').textContent='🔊 Hear & Spell';$('#promptArea').innerHTML=`<h2>Listen to the word</h2><p class="instruction">Tap the sound button, then type what you hear.</p><button class="speak-btn" aria-label="Hear the word and example sentence">🔊</button><p class="sentence">The word and an example sentence will be read aloud.</p>`;$('#answerArea').innerHTML=spellForm();$('.speak-btn').onclick=()=>speak(word,sentence);setTimeout(()=>speak(word,sentence),250)}
  else if(q.mode===1){const hidden=hideLetters(word);$('#modeBadge').textContent='🧩 Missing Letters';$('#promptArea').innerHTML=`<h2>Complete the word</h2><p class="instruction">Say it slowly and fill in the missing letters.</p><div class="letters">${[...hidden].map(c=>`<span class="letter ${c==='_'?'blank':''}">${c}</span>`).join('')}</div><button class="quiet hear-small">🔊 Hear the word</button>`;$('#answerArea').innerHTML=spellForm();$('.hear-small').onclick=()=>speak(word,sentence)}
  else{$('#modeBadge').textContent='⚡ Word Smash';$('#promptArea').innerHTML=`<h2>Spot the correct spelling</h2><p class="instruction">Which word is spelled correctly?</p><button class="quiet hear-small">🔊 Hear the word</button>`;$('#answerArea').innerHTML=`<div class="choices">${makeChoices(word).map(x=>`<button class="choice" data-answer="${x}">${x}</button>`).join('')}</div>`;$('.hear-small').onclick=()=>speak(word,sentence);$$('.choice').forEach(b=>b.onclick=()=>submit(b.dataset.answer))}
  const form=$('.spell-form');if(form){form.onsubmit=e=>{e.preventDefault();submit($('.spell-input').value)};setTimeout(()=>$('.spell-input').focus(),50)}
}
function spellForm(){return '<form class="spell-form"><input class="spell-input" autocomplete="off" autocapitalize="none" spellcheck="false" aria-label="Type the spelling"><button class="primary">Check</button></form>'}
function hideLetters(w){let chars=[...w];let positions=chars.map((_,i)=>i).filter(i=>i>0&&i<chars.length-1);positions.sort(()=>Math.random()-.5).slice(0,Math.max(2,Math.floor(w.length*.35))).forEach(i=>chars[i]='_');return chars.join('')}
function makeChoices(w){const variants=new Set([w]);const transforms=[x=>x.replace(/([aeiou])/,''),x=>x.slice(0,-1)+x.at(-1)+x.at(-1),x=>x.replace(/ie/,'ei'),x=>x.replace(/ou/,'u'),x=>x.replace(/([bcdfgmnprst])\1/, '$1'),x=>x.slice(0,2)+x[2]+x.slice(2)];for(const f of transforms){if(variants.size<4){const v=f(w);if(v!==w)variants.add(v)}}while(variants.size<4)variants.add(w+'e'.repeat(variants.size));return [...variants].sort(()=>Math.random()-.5)}
function normalise(x){return x.trim().toLowerCase().replace(/[^a-z'-]/g,'')}
function submit(answer){if(state.locked)return;state.locked=true;const q=current(),rec=state.records[q.data.word];rec.attempts++;const right=normalise(answer)===q.data.word;if(rec.firstCorrect===null)rec.firstCorrect=right;if(right){rec.correct=true;state.coins+=5;state.xp+=10;setFeedback(['Brilliant spelling!','Word magic!','You found it!'][Math.floor(Math.random()*3)],true);$('#owlFace').textContent='🦉✨';setTimeout(()=>{state.index++;renderQuestion()},900)}else{rec.correct=false;if(!q.repeat&&!q.scheduled){q.scheduled=true;state.queue.splice(Math.min(state.queue.length,state.index+3),0,{data:q.data,mode:(q.mode+1)%3,repeat:true})}showCorrection(q)}}
function showCorrection(q){const word=q.data.word;$('#feedback').innerHTML=`<div class="correction"><span>Good try! The correct spelling is</span><strong>${word}</strong><small>Type it once more to help your brain remember it.</small></div>`;$('#feedback').className='feedback try';$('#answerArea').innerHTML=`<form class="spell-form correction-form"><input class="spell-input" autocomplete="off" autocapitalize="none" spellcheck="false" aria-label="Type the correct spelling again"><button class="primary">Try again</button></form><button class="secondary next-word">Next word →</button>`;$('#owlText').textContent='Take your time. Look at the word, say it, then type it again.';speak(word,q.data.sentence);$('.correction-form').onsubmit=e=>{e.preventDefault();const input=$('.correction-form .spell-input');if(normalise(input.value)===word){state.records[word].correct=true;state.coins+=3;state.xp+=5;$('#feedback').textContent='✓ That’s it! You helped your memory grow.';$('#feedback').className='feedback good';$('#owlFace').textContent='🦉✨';setTimeout(()=>{state.index++;renderQuestion()},1100)}else{input.value='';input.focus();$('#owlText').textContent=`Look carefully: ${word}. Copy each letter when you’re ready.`}};$('.next-word').onclick=()=>{state.index++;renderQuestion()};setTimeout(()=>{$('.correction-form .spell-input')?.focus();state.locked=false},100)}
function setFeedback(text,good){const el=$('#feedback');el.textContent=(good?'✓ ':'🌱 ')+text;el.className='feedback '+(good?'good':'try')}
function startBoss(){const records=Object.entries(state.records);const needs=records.filter(([,r])=>!r.firstCorrect).map(([w])=>w);const all=records.map(([w])=>w);const chosen=[...needs,...all.filter(w=>!needs.includes(w))].slice(0,5);state.boss=chosen;state.bossIndex=0;show('boss');renderBoss()}
function renderBoss(){if(state.bossIndex>=5){finish();return}const word=state.boss[state.bossIndex],data=getWords().find(x=>x.word===word)||{word,sentence:`Spell ${word}.`};$('#bossProgress').textContent=`${state.bossIndex+1} / 5`;$('#bossFeedback').textContent='';$('#bossChallenge').innerHTML=`<h3>Listen, then spell the word</h3><button class="speak-btn" aria-label="Hear the word">🔊</button><form class="spell-form"><input class="spell-input" autocomplete="off" autocapitalize="none" spellcheck="false" aria-label="Type the spelling"><button class="primary">Cast spell!</button></form>`;$('#bossChallenge .speak-btn').onclick=()=>speak(word,data.sentence);$('#bossChallenge form').onsubmit=e=>{e.preventDefault();submitBoss($('.boss-card .spell-input').value)};setTimeout(()=>speak(word,data.sentence),200)}
function submitBoss(answer){const word=state.boss[state.bossIndex];if(normalise(answer)===word){state.bossCorrect++;state.coins+=10;state.xp+=15;$('#bossFeedback').textContent='✨ The forest glows brighter!';$('#bossFeedback').className='feedback good'}else{$('#bossFeedback').textContent=`🌱 Nearly! It’s “${word}”. Every try builds memory.`;$('#bossFeedback').className='feedback try';speak(word)}setTimeout(()=>{state.bossIndex++;renderBoss()},1300)}
function finish(){const first=Object.values(state.records).filter(r=>r.firstCorrect).length,stars=first>=8?3:first>=5?2:1;const result={date:new Date().toISOString(),records:state.records,attempts:Object.values(state.records).reduce((n,r)=>n+r.attempts,0)+5,firstCorrect:first,coins:state.coins,stars,xp:state.xp,bossCorrect:state.bossCorrect};saved.latest=result;saved.totalCoins=(saved.totalCoins||0)+state.coins;saved.totalStars=(saved.totalStars||0)+stars;localStorage.setItem('spellQuest',JSON.stringify(saved));$('#coinCount').textContent=saved.totalCoins;$('#starCount').textContent=saved.totalStars;$('#resultStars').textContent='⭐'.repeat(stars);$('#resultCoins').textContent='+'+state.coins;$('#resultWords').textContent=`${first}/${Object.keys(state.records).length}`;show('results')}
function renderParent(){const r=saved.latest;$('#emptyResults').hidden=!!r;$('#dashboard').hidden=!r;renderPlanner();if(!r)return;const entries=Object.entries(r.records);$('#pAttempts').textContent=r.attempts;$('#pAccuracy').textContent=Math.round(r.firstCorrect/entries.length*100)+'%';$('#pMastered').textContent=`${entries.filter(([,x])=>x.correct).length} / ${entries.length}`;$('#pStars').textContent=r.stars;$('#wordResults').innerHTML=entries.map(([w,x])=>`<span class="word-chip ${x.firstCorrect?'good':'practise'}">${x.firstCorrect?'✓':'↻'} ${w}</span>`).join('');const pats={};entries.filter(([,x])=>!x.firstCorrect).forEach(([w])=>{const d=getWords().find(x=>x.word===w);const p=d?.pattern||guessPattern(w);pats[p]=(pats[p]||0)+1});$('#patterns').innerHTML=Object.keys(pats).length?Object.entries(pats).sort((a,b)=>b[1]-a[1]).map(([p,n])=>`<div class="pattern"><span>${p}</span><b>${n} word${n>1?'s':''}</b></div>`).join(''):'<p>✨ No tricky patterns this time — lovely work!</p>'}
function allBankWords(){return [...new Set([...WORD_BANK,...BUILT_IN.map(x=>x.word),...(saved.importedBank||[])])].sort()}
function persist(){localStorage.setItem('spellQuest',JSON.stringify(saved))}
function renderPlanner(){saved.weeklyPlan=saved.weeklyPlan||{};$('#activeWeek').innerHTML=Array.from({length:10},(_,i)=>`<option value="${i+1}">Week ${i+1}</option>`).join('');$('#activeWeek').value=currentWeek();$('#customWords').value=planWords().join(', ');$('#bankSummary').textContent=`${allBankWords().length} Year 3/4 and imported words ready`;$('#weekPreview').innerHTML=Array.from({length:10},(_,i)=>{const n=i+1,w=planWords(n);return `<button class="week-tile ${n===currentWeek()?'active':''}" data-week="${n}"><b>Week ${n}</b><small>${w.length?`${w.length} words · ${w.slice(0,2).join(', ')}`:'Not planned'}</small></button>`}).join('');$$('.week-tile').forEach(b=>b.onclick=()=>selectWeek(Number(b.dataset.week)))}
function selectWeek(n){saved.activeWeek=n;persist();renderPlanner()}
function parsedWords(text){return [...new Set(text.toLowerCase().split(/[\n,;]+/).map(normalise).filter(w=>w.length>1))].slice(0,1000)}
function randomWords(count,used=[]){const stamp=Number(saved.weekStamp)||1,h=saved.wordHistory||{};let pool=allBankWords().filter(w=>!used.includes(w)&&(!h[w]||stamp-h[w]>=4));if(pool.length<count)pool=allBankWords().filter(w=>!used.includes(w));return pool.sort(()=>Math.random()-.5).slice(0,count)}
$('#activeWeek').onchange=e=>selectWeek(Number(e.target.value));
$('#saveWords').onclick=()=>{const words=parsedWords($('#customWords').value);if(words.length<5){$('#saveStatus').textContent='Please add at least 5 words.';return}saved.weeklyPlan=saved.weeklyPlan||{};saved.weeklyPlan[currentWeek()]=words;persist();renderPlanner();$('#saveStatus').textContent=`✓ ${words.length} words saved for week ${currentWeek()}.`};
$('#clearWords').onclick=()=>{saved.weeklyPlan=saved.weeklyPlan||{};delete saved.weeklyPlan[currentWeek()];persist();renderPlanner();$('#saveStatus').textContent=`Week ${currentWeek()} cleared.`};
$('#randomWeek').onclick=()=>{saved.weeklyPlan=saved.weeklyPlan||{};const recent=[1,2,3].flatMap(back=>planWords(currentWeek()-back));saved.weeklyPlan[currentWeek()]=randomWords(10,recent);persist();renderPlanner();$('#saveStatus').textContent=`✓ Week ${currentWeek()} randomised with no recent repeats.`};
$('#randomPlan').onclick=()=>{saved.weeklyPlan={};let used=[];for(let w=1;w<=10;w++){const words=randomWords(10,used.slice(-30));saved.weeklyPlan[w]=words;used.push(...words)}persist();renderPlanner();$('#saveStatus').textContent='✓ A complete 10-week plan is ready.'};
$('#nextWeek').onclick=()=>{saved.activeWeek=currentWeek()===10?1:currentWeek()+1;saved.weekStamp=(Number(saved.weekStamp)||1)+1;persist();renderPlanner();$('#saveStatus').textContent=`Now using week ${currentWeek()}.`};
async function importSheet(file){try{if(!window.XLSX)throw new Error('Spreadsheet reader unavailable. Check your internet connection.');const data=await file.arrayBuffer(),book=XLSX.read(data),sheet=book.Sheets[book.SheetNames[0]],rows=XLSX.utils.sheet_to_json(sheet,{header:1,defval:''});if(!rows.length)throw new Error('The spreadsheet is empty.');const header=rows[0].map(x=>String(x).trim().toLowerCase()),wi=header.findIndex(x=>/word|spelling|keyword/.test(x)),weeki=header.findIndex(x=>/week/.test(x)),start=wi>=0?1:0,wordCol=wi>=0?wi:0;let imported=[];saved.weeklyPlan=saved.weeklyPlan||{};for(const row of rows.slice(start)){const word=normalise(String(row[wordCol]||''));if(word.length<2)continue;imported.push(word);if(weeki>=0){const week=Math.max(1,Math.min(10,parseInt(row[weeki])||currentWeek()));saved.weeklyPlan[week]=[...new Set([...(saved.weeklyPlan[week]||[]),word])]}}saved.importedBank=[...new Set([...(saved.importedBank||[]),...imported])];if(weeki<0)saved.weeklyPlan[currentWeek()]=[...new Set([...planWords(),...imported])].slice(0,100);persist();renderPlanner();$('#saveStatus').textContent=`✓ Imported ${imported.length} words from ${file.name}.`}catch(err){$('#saveStatus').textContent=err.message}}
$('#fileInput').onchange=e=>e.target.files[0]&&importSheet(e.target.files[0]);const dz=$('#dropZone');['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>{const f=e.dataTransfer.files[0];if(f)importSheet(f)});

