const BUILT_IN = [
  {word:'because',sentence:'I wore my coat because it was cold.',pattern:'because'},
  {word:'beautiful',sentence:'The peacock has beautiful feathers.',pattern:'-ful ending'},
  {word:'different',sentence:'The two shells look different.',pattern:'double consonants'},
  {word:'important',sentence:'It is important to listen carefully.',pattern:'-ant ending'},
  {word:'thought',sentence:'I thought about the answer.',pattern:'-ough sound'},
  {word:'enough',sentence:'There is enough cake for everyone.',pattern:'-ough sound'},
  {word:'favourite',sentence:'Blue is my favourite colour.',pattern:'our spelling'},
  {word:'remember',sentence:'Remember to bring your reading book.',pattern:'prefix re-'},
  {word:'straight',sentence:'Draw a straight line with your ruler.',pattern:'-aigh sound'},
  {word:'surprise',sentence:'The party was a lovely surprise.',pattern:'-prise ending'}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let state={queue:[],index:0,records:{},coins:0,xp:0,boss:[],bossIndex:0,bossCorrect:0,locked:false};
const saved=JSON.parse(localStorage.getItem('spellQuest')||'{}');
$('#coinCount').textContent=saved.totalCoins||0; $('#starCount').textContent=saved.totalStars||0;
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id+'Screen').classList.add('active');scrollTo(0,0);if(id==='parent')renderParent()}
$$('[data-nav]').forEach(b=>b.onclick=()=>show(b.dataset.nav));
function getWords(){const c=(saved.customWords||[]).filter(Boolean);return (c.length>=5?c.map(word=>({word,sentence:`Can you spell the word ${word}?`,pattern:guessPattern(word)})):BUILT_IN).slice(0,15)}
function guessPattern(w){if(/ough/.test(w))return '-ough sound';if(/tion/.test(w))return '-tion ending';if(/ful$/.test(w))return '-ful ending';if(/ly$/.test(w))return '-ly ending';if(/([a-z])\1/.test(w))return 'double consonants';return 'whole word'}
function start(){const words=getWords();state={queue:words.slice(0,10).map((data,i)=>({data,mode:i%3,repeat:false})),index:0,records:{},coins:0,xp:0,boss:[],bossIndex:0,bossCorrect:0,locked:false};words.slice(0,10).forEach(x=>state.records[x.word]={attempts:0,firstCorrect:null,correct:false});show('game');renderQuestion()}
$('#startBtn').onclick=start;$('#playAgain').onclick=start;$('#exitBtn').onclick=()=>show('home');
function speak(word,sentence=''){if(!('speechSynthesis'in window)){setFeedback('Your browser cannot speak, but you can still play.',false);return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(sentence?`${word}. ${sentence}`:word);u.lang='en-GB';u.rate=.78;speechSynthesis.speak(u)}
function current(){return state.queue[state.index]}
function renderQuestion(){state.locked=false;const q=current();if(!q){startBoss();return}const {word,sentence}=q.data;$('#roundLabel').textContent=`Quest ${Math.min(state.index+1,10)} of 10`;$('#xpLabel').textContent=`${state.xp} XP`;$('#progressBar').style.width=`${Math.min(100,(state.index/state.queue.length)*100)}%`;$('#feedback').textContent='';$('#feedback').className='feedback';$('#owlText').textContent=q.repeat?'This one is back for another try — you’ve got this!':'I’m with you! Have a go.';
  if(q.mode===0){$('#modeBadge').textContent='🔊 Hear & Spell';$('#promptArea').innerHTML=`<h2>Listen to the word</h2><p class="instruction">Tap the sound button, then type what you hear.</p><button class="speak-btn" aria-label="Hear the word and example sentence">🔊</button><p class="sentence">The word and an example sentence will be read aloud.</p>`;$('#answerArea').innerHTML=spellForm();$('.speak-btn').onclick=()=>speak(word,sentence);setTimeout(()=>speak(word,sentence),250)}
  else if(q.mode===1){const hidden=hideLetters(word);$('#modeBadge').textContent='🧩 Missing Letters';$('#promptArea').innerHTML=`<h2>Complete the word</h2><p class="instruction">Say it slowly and fill in the missing letters.</p><div class="letters">${[...hidden].map(c=>`<span class="letter ${c==='_'?'blank':''}">${c}</span>`).join('')}</div><button class="quiet hear-small">🔊 Hear the word</button>`;$('#answerArea').innerHTML=spellForm();$('.hear-small').onclick=()=>speak(word,sentence)}
  else{$('#modeBadge').textContent='⚡ Word Smash';$('#promptArea').innerHTML=`<h2>Spot the correct spelling</h2><p class="instruction">Which word is spelled correctly?</p><button class="quiet hear-small">🔊 Hear the word</button>`;$('#answerArea').innerHTML=`<div class="choices">${makeChoices(word).map(x=>`<button class="choice" data-answer="${x}">${x}</button>`).join('')}</div>`;$('.hear-small').onclick=()=>speak(word,sentence);$$('.choice').forEach(b=>b.onclick=()=>submit(b.dataset.answer))}
  const form=$('.spell-form');if(form){form.onsubmit=e=>{e.preventDefault();submit($('.spell-input').value)};setTimeout(()=>$('.spell-input').focus(),50)}
}
function spellForm(){return '<form class="spell-form"><input class="spell-input" autocomplete="off" autocapitalize="none" spellcheck="false" aria-label="Type the spelling"><button class="primary">Check</button></form>'}
function hideLetters(w){let chars=[...w];let positions=chars.map((_,i)=>i).filter(i=>i>0&&i<chars.length-1);positions.sort(()=>Math.random()-.5).slice(0,Math.max(2,Math.floor(w.length*.35))).forEach(i=>chars[i]='_');return chars.join('')}
function makeChoices(w){const variants=new Set([w]);const transforms=[x=>x.replace(/([aeiou])/,''),x=>x.slice(0,-1)+x.at(-1)+x.at(-1),x=>x.replace(/ie/,'ei'),x=>x.replace(/ou/,'u'),x=>x.replace(/([bcdfgmnprst])\1/, '$1'),x=>x.slice(0,2)+x[2]+x.slice(2)];for(const f of transforms){if(variants.size<4){const v=f(w);if(v!==w)variants.add(v)}}while(variants.size<4)variants.add(w+'e'.repeat(variants.size));return [...variants].sort(()=>Math.random()-.5)}
function normalise(x){return x.trim().toLowerCase().replace(/[^a-z'-]/g,'')}
function submit(answer){if(state.locked)return;state.locked=true;const q=current(),rec=state.records[q.data.word];rec.attempts++;const right=normalise(answer)===q.data.word;if(rec.firstCorrect===null)rec.firstCorrect=right;if(right){rec.correct=true;state.coins+=5;state.xp+=10;setFeedback(['Brilliant spelling!','Word magic!','You found it!'][Math.floor(Math.random()*3)],true);$('#owlFace').textContent='🦉✨';setTimeout(()=>{state.index++;renderQuestion()},900)}else{rec.correct=false;setFeedback(`Good try! The word is “${q.data.word}”. We’ll see it again soon.`,false);$('#owlText').textContent='Mistakes help your brain grow. Say it, look at it, then try it again soon.';speak(q.data.word,q.data.sentence);if(!q.repeat)state.queue.splice(Math.min(state.queue.length,state.index+3),0,{data:q.data,mode:(q.mode+1)%3,repeat:true});setTimeout(()=>{state.index++;renderQuestion()},1800)}}
function setFeedback(text,good){const el=$('#feedback');el.textContent=(good?'✓ ':'🌱 ')+text;el.className='feedback '+(good?'good':'try')}
function startBoss(){const records=Object.entries(state.records);const needs=records.filter(([,r])=>!r.firstCorrect).map(([w])=>w);const all=records.map(([w])=>w);const chosen=[...needs,...all.filter(w=>!needs.includes(w))].slice(0,5);state.boss=chosen;state.bossIndex=0;show('boss');renderBoss()}
function renderBoss(){if(state.bossIndex>=5){finish();return}const word=state.boss[state.bossIndex],data=getWords().find(x=>x.word===word)||{word,sentence:`Spell ${word}.`};$('#bossProgress').textContent=`${state.bossIndex+1} / 5`;$('#bossFeedback').textContent='';$('#bossChallenge').innerHTML=`<h3>Listen, then spell the word</h3><button class="speak-btn" aria-label="Hear the word">🔊</button><form class="spell-form"><input class="spell-input" autocomplete="off" autocapitalize="none" spellcheck="false" aria-label="Type the spelling"><button class="primary">Cast spell!</button></form>`;$('#bossChallenge .speak-btn').onclick=()=>speak(word,data.sentence);$('#bossChallenge form').onsubmit=e=>{e.preventDefault();submitBoss($('.boss-card .spell-input').value)};setTimeout(()=>speak(word,data.sentence),200)}
function submitBoss(answer){const word=state.boss[state.bossIndex];if(normalise(answer)===word){state.bossCorrect++;state.coins+=10;state.xp+=15;$('#bossFeedback').textContent='✨ The forest glows brighter!';$('#bossFeedback').className='feedback good'}else{$('#bossFeedback').textContent=`🌱 Nearly! It’s “${word}”. Every try builds memory.`;$('#bossFeedback').className='feedback try';speak(word)}setTimeout(()=>{state.bossIndex++;renderBoss()},1300)}
function finish(){const first=Object.values(state.records).filter(r=>r.firstCorrect).length,stars=first>=8?3:first>=5?2:1;const result={date:new Date().toISOString(),records:state.records,attempts:Object.values(state.records).reduce((n,r)=>n+r.attempts,0)+5,firstCorrect:first,coins:state.coins,stars,xp:state.xp,bossCorrect:state.bossCorrect};saved.latest=result;saved.totalCoins=(saved.totalCoins||0)+state.coins;saved.totalStars=(saved.totalStars||0)+stars;localStorage.setItem('spellQuest',JSON.stringify(saved));$('#coinCount').textContent=saved.totalCoins;$('#starCount').textContent=saved.totalStars;$('#resultStars').textContent='⭐'.repeat(stars);$('#resultCoins').textContent='+'+state.coins;$('#resultWords').textContent=`${first}/${Object.keys(state.records).length}`;show('results')}
function renderParent(){const r=saved.latest;$('#emptyResults').hidden=!!r;$('#dashboard').hidden=!r;$('#customWords').value=(saved.customWords||[]).join(', ');if(!r)return;const entries=Object.entries(r.records);$('#pAttempts').textContent=r.attempts;$('#pAccuracy').textContent=Math.round(r.firstCorrect/entries.length*100)+'%';$('#pMastered').textContent=`${entries.filter(([,x])=>x.correct).length} / ${entries.length}`;$('#pStars').textContent=r.stars;$('#wordResults').innerHTML=entries.map(([w,x])=>`<span class="word-chip ${x.firstCorrect?'good':'practise'}">${x.firstCorrect?'✓':'↻'} ${w}</span>`).join('');const pats={};entries.filter(([,x])=>!x.firstCorrect).forEach(([w])=>{const d=getWords().find(x=>x.word===w);const p=d?.pattern||guessPattern(w);pats[p]=(pats[p]||0)+1});$('#patterns').innerHTML=Object.keys(pats).length?Object.entries(pats).sort((a,b)=>b[1]-a[1]).map(([p,n])=>`<div class="pattern"><span>${p}</span><b>${n} word${n>1?'s':''}</b></div>`).join(''):'<p>✨ No tricky patterns this time — lovely work!</p>'}
$('#saveWords').onclick=()=>{const words=$('#customWords').value.toLowerCase().split(/[\n,]+/).map(w=>normalise(w)).filter((w,i,a)=>w.length>1&&a.indexOf(w)===i).slice(0,15);if(words.length<5){$('#saveStatus').textContent='Please add at least 5 words.';return}saved.customWords=words;localStorage.setItem('spellQuest',JSON.stringify(saved));$('#saveStatus').textContent=`✓ ${words.length} words saved for the next quest.`};
$('#clearWords').onclick=()=>{saved.customWords=[];localStorage.setItem('spellQuest',JSON.stringify(saved));$('#customWords').value='';$('#saveStatus').textContent='✓ Built-in word list restored.'};

