const BUILT_IN = [
  {word:'because',sentence:'I wore my coat because it was cold.',pattern:'because'},
  {word:'beautiful',sentence:'The peacock has beautiful feathers.',pattern:'-ful ending'},
  {word:'different',sentence:'The two shells look different.',pattern:'double consonants'},
  {word:'important',sentence:'It is important to listen carefully.',pattern:'-ant ending'},
  {word:'thought',sentence:'I thought about the answer.',pattern:'-ough sound'},
  {word:'enough',sentence:'There is enough cake for everyone.',pattern:'-ough sound'},
  {word:'favourite',sentence:'Blue is my favourite colour.',pattern:'our spelling'},
  {word:'remember',sentence:'Remember to bring your reading book.',pattern:'prefix re-'},
  {word:'straight',sentence:'Draw a straight line with your ruler.',pattern:'-aigh sound'},
  {word:'surprise',sentence:'The party was a lovely surprise.',pattern:'-prise ending'}
];
const WORD_HELP = {
  because:{sounds:['b','e','c','au','se'],syllables:['be','cause'],parts:['be','cause'],tricky:'au',tip:'Think: big elephants can always understand small elephants.'},
  beautiful:{sounds:['beau','ti','ful'],syllables:['beau','ti','ful'],parts:['beau','ti','ful'],tricky:'eau',build:['b','be','bea','beau'],teaching:'Beautiful. Beau, ti, ful. The first part is spelled B, E, A, U. Beau. Then T, I. Then F, U, L.',tip:'The unusual beginning is beau. Build it one letter at a time: b, be, bea, beau. Then add ti and ful.'},
  different:{sounds:['dif','fer','ent'],syllables:['dif','fer','ent'],parts:['differ','ent'],tricky:'ff',tip:'It begins with differ, as in two things differ.'},
  important:{sounds:['im','por','tant'],syllables:['im','por','tant'],parts:['import','ant'],tricky:'ant',tip:'The ending is ant, like the small insect.'},
  thought:{sounds:['th','ough','t'],syllables:['thought'],parts:['th','ought'],tricky:'ough',tip:'The four letters ough work together in this word.'},
  enough:{sounds:['e','n','ough'],syllables:['e','nough'],parts:['en','ough'],tricky:'ough',tip:'Enough ends with ough, even though it sounds like “uff”.'},
  favourite:{sounds:['fav','our','ite'],syllables:['fav','our','ite'],parts:['favour','ite'],tricky:'our',tip:'In British English, favourite keeps the u in favour.'},
  remember:{sounds:['re','mem','ber'],syllables:['re','mem','ber'],parts:['re','member'],tricky:'mem',tip:'Re + member: remember to keep the whole word member.'},
  straight:{sounds:['str','aigh','t'],syllables:['straight'],parts:['str','aight'],tricky:'aigh',tip:'Straight has the word eight at the end with “stra” in front.'},
  surprise:{sounds:['sur','prise'],syllables:['sur','prise'],parts:['sur','prise'],tricky:'rpr',tip:'There is an r before and after the first p: sur-pri-se.'}
};
const WORLDS=[
  ['🌿','Sound Trail',['Sound detectives','Vowel teams','Long and short sounds','Consonant teams','Sound Trail review']],
  ['💧','Suffix Springs',['Adding -ful and -less','Adding -ly','Adding -ment and -ness','Changing root words','Suffix Springs review']],
  ['⛰️','Prefix Peaks',['re- and dis-','mis- and in-','sub- and inter-','Word families','Prefix Peaks review']],
  ['⚓','Homophone Harbour',['Here or hear?','There, their and they’re','To, too and two','Meaning chooses spelling','Homophone Harbour review']],
  ['🏰','Tricky Word Tower',['Unexpected vowels','Silent letters','The many sounds of -ough','Commonly confused words','Tricky Word review']],
  ['🌟','Mastery Mountain',['Roots and relatives','Syllable strategies','Words in sentences','Cumulative recall','Wordwood champion']]
];
const WORD_BANK = `accident actual address answer appear arrive believe bicycle breath breathe build busy business calendar caught centre century certain circle complete consider continue decide describe disappear early earth eight eighth exercise experience experiment extreme famous February forward fruit grammar group guard guide heard heart height history imagine increase interest island knowledge learn length library material medicine mention minute natural naughty notice occasion occasionally often opposite ordinary particular peculiar perhaps popular position possess possession possible potatoes pressure probably promise purpose quarter question recent regular reign sentence separate special strange strength suppose therefore though although through various weight woman women`.toLowerCase().split(' ');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let state={queue:[],index:0,records:{},coins:0,xp:0,boss:[],bossIndex:0,bossCorrect:0,locked:false,questType:'main',activeWords:[]};
const saved=JSON.parse(localStorage.getItem('spellQuest')||'{}');
if(!saved.weeklyWords){const legacy=((saved.weeklyPlan||{})[Number(saved.activeWeek)||1]||[]).filter(Boolean);if(legacy.length)saved.weeklyWords=legacy}
$('#coinCount').textContent=saved.totalCoins||0; $('#starCount').textContent=saved.totalStars||0;
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id+'Screen').classList.add('active');scrollTo(0,0);if(id==='home')renderWeeklyEntrances();if(id==='parent')renderParent();if(id==='map')renderMap()}
$$('[data-nav]').forEach(b=>b.onclick=()=>show(b.dataset.nav));
$('#mapBtn').onclick=()=>show('map');
function renderMap(){const complete=saved.completedQuests||[];let n=0;$('#questWorlds').innerHTML=`<div class="forest-decor" aria-hidden="true"><span>🦉</span><span>🐿️</span><span>🦋</span><span>🦊</span></div><div class="trail-start">🏕️ START HERE</div>`+WORLDS.map(([icon,name,quests],world)=>`<section class="world-row world-${world+1}"><div class="world-title"><span>${icon}</span><div><h3>${name}</h3><small>Quests ${n+1}–${n+5}</small></div></div><div class="quest-track">${quests.map(title=>{n++;const status=complete.includes(n)?'complete':n===1?'ready':'locked';return `<button class="quest-node ${status}" data-quest="${n}" ${status==='locked'?'disabled':''}><b>${status==='complete'?'✓':status==='locked'?'🔒':'●'} ${n}</b><span>${title}</span><small>${n===1?'PLAY':status==='complete'?'DONE':'SOON'}</small>${n===1?'<i class="player-marker">🐲<em>You are here</em></i>':''}</button>`}).join('')}</div><div class="world-landmark" aria-hidden="true">${['🍄🌲','🌊🪷','⛰️🌲','⛵⚓','🏰🌙','⭐🏆'][world]}</div></section>`).join('')+`<div class="trail-finish">🏆 WORDWOOD CHAMPION</div>`;$$('.quest-node.ready').forEach(b=>b.onclick=()=>start('main'));renderWeeklyEntrances()}
function weeklyWords(){return (saved.weeklyWords||[]).filter(Boolean)}
function wordData(words){return words.map(word=>({word,sentence:`Can you spell ${word}?`,pattern:guessPattern(word)}))}
function getWords(type=state.questType){return type==='weekly'?wordData(weeklyWords()).slice(0,20):BUILT_IN}
function renderWeeklyEntrances(){const words=weeklyWords(),ready=words.length>=3,preview=words.slice(0,6).join(' · ')+(words.length>6?'…':'');if($('#weeklyHomeCard')){$('#weeklyHomeCard').hidden=!ready;$('#weeklyHomeTitle').textContent=`${words.length} school word${words.length===1?'':'s'} are ready!`;$('#weeklyHomeWords').textContent=preview}if($('#weeklyMapCard')){$('#weeklyMapCard').hidden=!ready;$('#weeklyMapWords').textContent=preview}}
function guessPattern(w){if(/ough/.test(w))return '-ough sound';if(/tion/.test(w))return '-tion ending';if(/ful$/.test(w))return '-ful ending';if(/ly$/.test(w))return '-ly ending';if(/([a-z])\1/.test(w))return 'double consonants';return 'whole word'}
function start(type='main'){const pool=getWords(type);if(type==='weekly'&&pool.length<3){show('parent');$('#saveStatus').textContent='Add at least 3 words to unlock the sidequest.';return}let words=pool.slice(0,10);if(type==='weekly'&&pool.length>10){const offset=(Number(saved.weeklyOffset)||0)%pool.length;words=Array.from({length:10},(_,i)=>pool[(offset+i)%pool.length]);saved.weeklyOffset=(offset+10)%pool.length;persist()}state={queue:words.map((data,i)=>({data,mode:i%3,repeat:false})),index:0,records:{},coins:0,xp:0,boss:[],bossIndex:0,bossCorrect:0,locked:false,questType:type,activeWords:words};words.forEach(x=>state.records[x.word]={attempts:0,firstCorrect:null,correct:false});show('game');renderQuestion()}
$('#startBtn').onclick=()=>start('main');$('#weeklyHomeStart').onclick=()=>start('weekly');$('#weeklyMapStart').onclick=()=>start('weekly');$('#parentSidequestStart').onclick=()=>start('weekly');$('#playAgain').onclick=()=>start(state.questType);$('#exitBtn').onclick=()=>show(state.questType==='weekly'?'home':'map');renderWeeklyEntrances();
function speak(word,sentence=''){if(!('speechSynthesis'in window)){setFeedback('Your browser cannot speak, but you can still play.',false);return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(sentence||word);u.lang='en-GB';u.rate=.78;speechSynthesis.speak(u)}
function current(){return state.queue[state.index]}
function renderQuestion(){state.locked=false;const q=current();if(!q){startBoss();return}const {word,sentence}=q.data,total=Object.keys(state.records).length;$('#roundLabel').textContent=`${state.questType==='weekly'?'Sidequest':'Quest'} ${Math.min(state.index+1,total)} of ${total}`;$('#xpLabel').textContent=`${state.xp} XP`;$('#progressBar').style.width=`${Math.min(100,(state.index/state.queue.length)*100)}%`;$('#feedback').textContent='';$('#feedback').className='feedback';$('#owlText').textContent=q.repeat?'This one is back for another try — you’ve got this!':'I’m with you! Have a go.';
  if(q.mode===0){$('#modeBadge').textContent='🔊 Hear & Spell';$('#promptArea').innerHTML=`<h2>Listen to the word</h2><p class="instruction">Tap the sound button, then type the spelling word you hear in the sentence.</p><button class="speak-btn" aria-label="Hear the example sentence">🔊</button><p class="sentence">The example sentence says the spelling word once.</p>`;$('#answerArea').innerHTML=spellForm();$('.speak-btn').onclick=()=>speak(word,sentence);setTimeout(()=>speak(word,sentence),250)}
  else if(q.mode===1){const hidden=hideLetters(word);$('#modeBadge').textContent='🧩 Missing Letters';$('#promptArea').innerHTML=`<h2>Complete the word</h2><p class="instruction">Say it slowly and fill in the missing letters.</p><div class="letters">${[...hidden].map(c=>`<span class="letter ${c==='_'?'blank':''}">${c}</span>`).join('')}</div><button class="quiet hear-small">🔊 Hear the word</button>`;$('#answerArea').innerHTML=spellForm();$('.hear-small').onclick=()=>speak(word,sentence)}
  else{$('#modeBadge').textContent='⚡ Word Smash';$('#promptArea').innerHTML=`<h2>Spot the correct spelling</h2><p class="instruction">Which word is spelled correctly?</p><button class="quiet hear-small">🔊 Hear the word</button>`;$('#answerArea').innerHTML=`<div class="choices">${makeChoices(word).map(x=>`<button class="choice" data-answer="${x}">${x}</button>`).join('')}</div>`;$('.hear-small').onclick=()=>speak(word,sentence);$$('.choice').forEach(b=>b.onclick=()=>submit(b.dataset.answer))}
  const form=$('.spell-form');if(form){form.onsubmit=e=>{e.preventDefault();submit($('.spell-input').value)};setTimeout(()=>$('.spell-input').focus(),50)}
}
function spellForm(){return '<form class="spell-form"><input class="spell-input" autocomplete="off" autocapitalize="none" spellcheck="false" aria-label="Type the spelling"><button class="primary">Check</button></form>'}
function hideLetters(w){let chars=[...w];let positions=chars.map((_,i)=>i).filter(i=>i>0&&i<chars.length-1);positions.sort(()=>Math.random()-.5).slice(0,Math.max(2,Math.floor(w.length*.35))).forEach(i=>chars[i]='_');return chars.join('')}
function makeChoices(w){const variants=new Set([w]);const transforms=[x=>x.replace(/([aeiou])/,''),x=>x.slice(0,-1)+x.at(-1)+x.at(-1),x=>x.replace(/ie/,'ei'),x=>x.replace(/ou/,'u'),x=>x.replace(/([bcdfgmnprst])\1/, '$1'),x=>x.slice(0,2)+x[2]+x.slice(2)];for(const f of transforms){if(variants.size<4){const v=f(w);if(v!==w)variants.add(v)}}while(variants.size<4)variants.add(w+'e'.repeat(variants.size));return [...variants].sort(()=>Math.random()-.5)}
function normalise(x){return x.trim().toLowerCase().replace(/[^a-z'-]/g,'')}
function submit(answer){if(state.locked)return;state.locked=true;const q=current(),rec=state.records[q.data.word];rec.attempts++;const right=normalise(answer)===q.data.word;if(rec.firstCorrect===null)rec.firstCorrect=right;if(right){rec.correct=true;state.coins+=5;state.xp+=10;setFeedback(['Brilliant spelling!','Word magic!','You found it!'][Math.floor(Math.random()*3)],true);$('#owlFace').textContent='🦉✨';setTimeout(()=>{state.index++;renderQuestion()},900)}else{rec.correct=false;if(!q.repeat&&!q.scheduled){q.scheduled=true;state.queue.splice(Math.min(state.queue.length,state.index+3),0,{data:q.data,mode:(q.mode+1)%3,repeat:true})}showCorrection(q)}}
function showCorrection(q){const word=q.data.word;$('#feedback').innerHTML=`<div class="correction"><span>Good try! The correct spelling is</span><strong>${highlightTricky(word)}</strong><small>Listen to the help, then type it once more.</small></div><p class="support-heading">Your first help is open below. Try another strategy if you need it.</p><div class="support-buttons"><button class="support-btn" data-help="sounds">👆 Sound steps</button><button class="support-btn" data-help="syllables">👏 Syllables</button><button class="support-btn" data-help="parts">🧩 Word parts</button><button class="support-btn" data-help="tip">💡 Memory clue</button></div><div id="supportPanel" class="support-panel"></div>`;$('#feedback').className='feedback try';$('#answerArea').innerHTML=`<form class="spell-form correction-form"><input class="spell-input" autocomplete="off" autocapitalize="none" spellcheck="false" aria-label="Type the correct spelling again"><button class="primary">Try again</button></form><button class="secondary next-word">Next word →</button>`;$('#owlText').textContent='Take your time. Listen, look at the chunks, then type the word again.';$$('.support-btn').forEach(b=>b.onclick=()=>showSupport(word,b.dataset.help));showSupport(word,'sounds');$('.correction-form').onsubmit=e=>{e.preventDefault();const input=$('.correction-form .spell-input');if(normalise(input.value)===word){state.records[word].correct=true;state.coins+=3;state.xp+=5;$('#feedback').textContent='✓ That’s it! You helped your memory grow.';$('#feedback').className='feedback good';$('#owlFace').textContent='🦉✨';setTimeout(()=>{state.index++;renderQuestion()},1100)}else{input.value='';input.focus();$('#owlText').textContent=`Look carefully: ${word}. Copy each letter when you’re ready.`}};$('.next-word').onclick=()=>{state.index++;renderQuestion()};setTimeout(()=>{$('.correction-form .spell-input')?.focus();state.locked=false},100)}
function highlightTricky(word){const tricky=WORD_HELP[word]?.tricky;if(!tricky||!word.includes(tricky))return word;return word.replace(tricky,`<span class="tricky-part">${tricky}</span>`)}
function showSupport(word,type){const help=WORD_HELP[word]||{sounds:[...word],syllables:[word],parts:[word],tip:'Look, say, cover, write and check the whole word.'},panel=$('#supportPanel');panel.hidden=false;if(type==='sounds'){panel.innerHTML=`<b>Listen and follow the sound chunks</b><p>Say the word slowly. Touch one box for each useful chunk.</p><div class="sound-chips">${help.sounds.map(x=>`<i>${x}</i>`).join('')}</div>${help.build?`<p><b>Build the tricky beginning one letter at a time:</b></p><div class="build-steps">${help.build.map((x,i)=>`<span><small>${i+1}</small>${x}</span>`).join('<b>→</b>')}</div><p class="letter-order">Letter order: ${help.build.at(-1).toUpperCase().split('').join(' – ')}</p>`:''}`;speak(help.teaching||`${word}. ${help.syllables.join('. ')}`)}else if(type==='syllables'){panel.innerHTML=`<b>Clap the syllables</b><p>${help.syllables.join(' · ')}</p><div class="sound-chips">${help.syllables.map(x=>`<i>${x}</i>`).join('')}</div>`}else if(type==='parts'){panel.innerHTML=`<b>Build from useful word chunks</b><p>Learn one chunk, then join the chunks in order.</p><div class="sound-chips">${help.parts.map(x=>`<i>${x}</i>`).join('')}</div>`}else panel.innerHTML=`<b>Memory clue</b><p>${help.tip}</p>`}
function setFeedback(text,good){const el=$('#feedback');el.textContent=(good?'✓ ':'🌱 ')+text;el.className='feedback '+(good?'good':'try')}
function startBoss(){const records=Object.entries(state.records);const needs=records.filter(([,r])=>!r.firstCorrect).map(([w])=>w);const all=records.map(([w])=>w);state.boss=[...needs,...all.filter(w=>!needs.includes(w))].slice(0,Math.min(5,all.length));state.bossIndex=0;$('#bossIntro').textContent=state.questType==='weekly'?'Finish with the school words that need the most attention.':'Spell five words to help Glowtail light the whole forest!';show('boss');renderBoss()}
function renderBoss(){if(state.bossIndex>=state.boss.length){finish();return}const word=state.boss[state.bossIndex],data=state.activeWords.find(x=>x.word===word)||{word,sentence:`Spell ${word}.`};$('#bossProgress').textContent=`${state.bossIndex+1} / ${state.boss.length}`;$('#bossFeedback').textContent='';$('#bossChallenge').innerHTML=`<h3>Listen, then spell the word</h3><button class="speak-btn" aria-label="Hear the word">🔊</button><form class="spell-form"><input class="spell-input" autocomplete="off" autocapitalize="none" spellcheck="false" aria-label="Type the spelling"><button class="primary">Cast spell!</button></form>`;$('#bossChallenge .speak-btn').onclick=()=>speak(word,data.sentence);$('#bossChallenge form').onsubmit=e=>{e.preventDefault();submitBoss($('.boss-card .spell-input').value)};setTimeout(()=>speak(word,data.sentence),200)}
function submitBoss(answer){const word=state.boss[state.bossIndex];if(normalise(answer)===word){state.bossCorrect++;state.coins+=10;state.xp+=15;$('#bossFeedback').textContent='✨ The forest glows brighter!';$('#bossFeedback').className='feedback good'}else{$('#bossFeedback').textContent=`🌱 Nearly! It’s “${word}”. Every try builds memory.`;$('#bossFeedback').className='feedback try';speak(word)}setTimeout(()=>{state.bossIndex++;renderBoss()},1300)}
function finish(){const total=Object.keys(state.records).length,first=Object.values(state.records).filter(r=>r.firstCorrect).length,ratio=first/total,stars=ratio>=.8?3:ratio>=.5?2:1,secure=ratio>=.8||(ratio>=.7&&state.bossCorrect>=Math.ceil(state.boss.length*.8));const result={date:new Date().toISOString(),type:state.questType,records:state.records,attempts:Object.values(state.records).reduce((n,r)=>n+r.attempts,0)+state.boss.length,firstCorrect:first,coins:state.coins,stars,xp:state.xp,bossCorrect:state.bossCorrect,secure};saved.latest=result;if(state.questType==='weekly')saved.weeklyLatest=result;else saved.mainLatest=result;saved.totalCoins=(saved.totalCoins||0)+state.coins;saved.totalStars=(saved.totalStars||0)+stars;if(secure&&state.questType==='main')saved.completedQuests=[...new Set([...(saved.completedQuests||[]),1])];persist();$('#coinCount').textContent=saved.totalCoins;$('#starCount').textContent=saved.totalStars;$('#resultStars').textContent='⭐'.repeat(stars);$('#resultCoins').textContent='+'+state.coins;$('#resultWords').textContent=`${first}/${total}`;const weekly=state.questType==='weekly';$('#resultEyebrow').textContent=weekly?'SIDEQUEST COMPLETE':'QUEST COMPLETE';$('#resultTitle').textContent=weekly?'Weekly words rescued!':'You lit up the Wordwood!';$('#resultUnlock').innerHTML=weekly?'<span>🏅</span><div><small>BONUS REWARD</small><b>School Word Hero badge earned!</b></div>':'<span>🎒</span><div><small>NEW REWARD</small><b>Explorer’s Pack unlocked!</b></div>';$('#resultMessage').textContent=weekly?(secure?'Brilliant work — this week’s words are looking secure!':'Great practice. The difficult words will be ready for another sidequest.'):(secure?'Quest 1 is secure! Tricky words will still return in later review.':'Brilliant learning. A short rescue mission will help the tricky words stick before moving on.');show('results')}
function renderParent(){const r=saved.latest;$('#emptyResults').hidden=!!r;$('#dashboard').hidden=!r;renderWeeklyEditor();if(!r)return;const entries=Object.entries(r.records);$('.parent-head p').textContent=`Latest results: ${r.type==='weekly'?'Weekly Word Sidequest':'Main Quest 1'}.`;$('#pAttempts').textContent=r.attempts;$('#pAccuracy').textContent=Math.round(r.firstCorrect/entries.length*100)+'%';$('#pMastered').textContent=`${entries.filter(([,x])=>x.correct).length} / ${entries.length}`;$('#pStars').textContent=r.stars;$('#wordResults').innerHTML=entries.map(([w,x])=>`<span class="word-chip ${x.firstCorrect?'good':'practise'}">${x.firstCorrect?'✓':'↻'} ${w}</span>`).join('');const pats={};entries.filter(([,x])=>!x.firstCorrect).forEach(([w])=>{const d=(r.type==='weekly'?wordData(weeklyWords()):BUILT_IN).find(x=>x.word===w);const p=d?.pattern||guessPattern(w);pats[p]=(pats[p]||0)+1});$('#patterns').innerHTML=Object.keys(pats).length?Object.entries(pats).sort((a,b)=>b[1]-a[1]).map(([p,n])=>`<div class="pattern"><span>${p}</span><b>${n} word${n>1?'s':''}</b></div>`).join(''):'<p>✨ No tricky patterns this time — lovely work!</p>'}
function persist(){localStorage.setItem('spellQuest',JSON.stringify(saved))}
function renderWeeklyEditor(){const words=weeklyWords(),ready=words.length>=3;$('#customWords').value=words.join(', ');$('#weeklyReadyBadge').textContent=ready?`✨ Sidequest ready · ${words.length} words`:'Add at least 3 words';$('#weeklyReadyBadge').classList.toggle('ready',ready);$('#weeklyPreview').innerHTML=words.length?`<small>CURRENT LIST</small><div>${words.map(w=>`<span>${w}</span>`).join('')}</div>`:'<p>Your saved words will appear here.</p>';$('#parentSidequestStart').hidden=!ready;renderWeeklyEntrances()}
function parsedWords(text){return [...new Set(text.toLowerCase().split(/[\n,;]+/).map(normalise).filter(w=>w.length>1))].slice(0,1000)}
$('#saveWords').onclick=()=>{const words=parsedWords($('#customWords').value);if(words.length<3){$('#saveStatus').textContent='Please add at least 3 words.';return}saved.weeklyWords=words.slice(0,20);persist();renderWeeklyEditor();$('#saveStatus').textContent=`✓ ${saved.weeklyWords.length} words saved. The Weekly Word Sidequest is ready.`};
$('#clearWords').onclick=()=>{saved.weeklyWords=[];persist();renderWeeklyEditor();$('#saveStatus').textContent='Weekly list cleared. The main quests are unchanged.'};
async function importSheet(file){try{if(!window.XLSX)throw new Error('Spreadsheet reader unavailable. Check your internet connection.');const data=await file.arrayBuffer(),book=XLSX.read(data),sheet=book.Sheets[book.SheetNames[0]],rows=XLSX.utils.sheet_to_json(sheet,{header:1,defval:''});if(!rows.length)throw new Error('The spreadsheet is empty.');const header=rows[0].map(x=>String(x).trim().toLowerCase()),wi=header.findIndex(x=>/word|spelling|keyword/.test(x)),start=wi>=0?1:0,wordCol=wi>=0?wi:0,imported=[];for(const row of rows.slice(start)){const word=normalise(String(row[wordCol]||''));if(word.length>1)imported.push(word)}saved.weeklyWords=[...new Set(imported)].slice(0,20);if(saved.weeklyWords.length<3)throw new Error('Please include at least 3 words in the first word or keyword column.');persist();renderWeeklyEditor();$('#saveStatus').textContent=`✓ Imported ${saved.weeklyWords.length} words from ${file.name}. Sidequest ready.`}catch(err){$('#saveStatus').textContent=err.message}}
$('#fileInput').onchange=e=>e.target.files[0]&&importSheet(e.target.files[0]);const dz=$('#dropZone');['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>{const f=e.dataTransfer.files[0];if(f)importSheet(f)});
